site_name: Clínica Odontológica Mariana
site_url: https://clinica-odontologica-mariana.github.io/docs

theme:
  name: material
  language: pt-BR

nav:
  - Início: index.md
  - Documentação: sobre.md
  - US: US.md